version: '2'
volumes:
  data:
services:

  db:
    container_name: 'oficina-legal-database'
    image: mysql:5.6
    ports:
      - 6001:3306
    volumes:
      - ./data/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=oficina-legal-config
    command: mysqld --innodb-buffer-pool-size=256M

  phpMyAdmin:
    container_name: 'oficina-legal-phpmyadmin'
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 3000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_PORT=6001