version: '2'
volumes:
  data:
services:

  db:
    container_name: 'oficina-legal-database'
    image: mysql:5.6
    ports:
      - 6001:3306
    volumes:
      - ./data/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=oficina-legal-dev
    command: mysqld --innodb-buffer-pool-size=256M

  phpMyAdmin:
    container_name: 'oficina-legal-phpmyadmin'
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 3000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_PORT=6001

  node-api:
    image: node:10
    container_name: 'oficina-legal-api'
    volumes:
      - ./oficina-legal-api:/app
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - NODE_ENV=develop
      - DB_DATABASE=oficina-legal-dev
      - DB_USERNAME=
      - DB_PASSWORD=
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DIALECT=mysql
      - cloudApiKey=
      - SECRET=
    links:
      - db
    command: bash -c "cd /app; npm ci; npm run start"
  
  angular-app:
    image: node:10
    container_name: 'oficina-legal-web'
    volumes:
      - ./oficina-legal-web-app:/app
    ports:
      - 5000:5000
    command: bash -c "cd /app; npm ci; npm run build; npm run start:prod"